"""add activities table

Revision ID: 04a876bd029e
Revises: 77b925dec5cf
Create Date: 2026-08-06 20:17:18.721086

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04a876bd029e"
down_revision = "77b925dec5cf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.Column("job_posting_id", sa.Integer(), nullable=True),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.Column(
            "activity_type",
            sa.Enum(
                "email",
                "linkedin_message",
                "phone_call",
                "interview",
                "networking",
                "recruiter_contact",
                "application_submitted",
                "follow_up",
                "research",
                "meeting",
                "other",
                name="activity_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "outbound",
                "inbound",
                "internal",
                name="activity_direction",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=300), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("follow_up_needed", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["job_posting_id"], ["job_postings.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activities_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(
            "ix_activities_application_occurred",
            ["application_id", "occurred_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_activities_contact_id"), ["contact_id"], unique=False
        )
        batch_op.create_index(
            "ix_activities_contact_occurred",
            ["contact_id", "occurred_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_activities_job_occurred",
            ["job_posting_id", "occurred_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_activities_job_posting_id"), ["job_posting_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activities_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activities_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_activities_organization_occurred",
            ["organization_id", "occurred_at"],
            unique=False,
        )
        batch_op.create_index("ix_activities_type", ["activity_type"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_index("ix_activities_type")
        batch_op.drop_index("ix_activities_organization_occurred")
        batch_op.drop_index(batch_op.f("ix_activities_organization_id"))
        batch_op.drop_index(batch_op.f("ix_activities_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_activities_job_posting_id"))
        batch_op.drop_index("ix_activities_job_occurred")
        batch_op.drop_index("ix_activities_contact_occurred")
        batch_op.drop_index(batch_op.f("ix_activities_contact_id"))
        batch_op.drop_index("ix_activities_application_occurred")
        batch_op.drop_index(batch_op.f("ix_activities_application_id"))

    op.drop_table("activities")
    # ### end Alembic commands ###
