"""empty message

Revision ID: 3fa1dda11764
Revises: b14f8e7c9a21
Create Date: 2026-08-06 22:17:54.446937

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3fa1dda11764"
down_revision = "b14f8e7c9a21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("activity_direction"), type_="check")
        batch_op.drop_constraint(batch_op.f("activity_type"), type_="check")

    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("application_status"), type_="check")

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("relationship_status"), type_="check")

    with op.batch_alter_table("job_postings", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("employment_type"), type_="check")
        batch_op.drop_constraint(batch_op.f("job_source"), type_="check")
        batch_op.drop_constraint(batch_op.f("job_status"), type_="check")
        batch_op.drop_constraint(batch_op.f("work_mode"), type_="check")

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("organization_type"), type_="check")

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("task_priority"), type_="check")
        batch_op.drop_constraint(batch_op.f("task_status"), type_="check")
        batch_op.drop_constraint(batch_op.f("task_type"), type_="check")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_check_constraint(
            batch_op.f("task_type"),
            "task_type IN ('follow_up', 'application', 'interview_preparation', 'research', 'networking', 'document_preparation', 'thank_you', 'portal_check', 'reminder', 'other')",
        )
        batch_op.create_check_constraint(
            batch_op.f("task_status"),
            "status IN ('open', 'in_progress', 'completed', 'cancelled')",
        )
        batch_op.create_check_constraint(
            batch_op.f("task_priority"),
            "priority IN ('low', 'medium', 'high', 'urgent')",
        )

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_check_constraint(
            batch_op.f("organization_type"),
            "organization_type IN ('hospital', 'research_institute', 'health_tech', 'medical_device', 'cro', 'university', 'recruiter', 'government')",
        )

    with op.batch_alter_table("job_postings", schema=None) as batch_op:
        batch_op.create_check_constraint(
            batch_op.f("work_mode"), "work_mode IN ('on_site', 'hybrid', 'remote')"
        )
        batch_op.create_check_constraint(
            batch_op.f("job_status"),
            "status IN ('discovered', 'researching', 'ready_to_apply', 'applied', 'closed', 'skipped')",
        )
        batch_op.create_check_constraint(
            batch_op.f("job_source"),
            "source IN ('company_website', 'linkedin', 'referral', 'recruiter', 'other')",
        )
        batch_op.create_check_constraint(
            batch_op.f("employment_type"),
            "employment_type IN ('full_time', 'part_time', 'contract', 'internship', 'temporary')",
        )

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_check_constraint(
            batch_op.f("relationship_status"),
            "relationship_status IN ('new', 'contacted', 'responded', 'interviewing', 'long_term_connection')",
        )

    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_check_constraint(
            batch_op.f("application_status"),
            "status IN ('planned', 'preparing', 'applied', 'screening', 'phone_interview', 'technical_interview', 'panel_interview', 'final_interview', 'offer', 'accepted', 'rejected', 'withdrawn')",
        )

    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.create_check_constraint(
            batch_op.f("activity_type"),
            "activity_type IN ('email', 'linkedin_message', 'phone_call', 'interview', 'networking', 'recruiter_contact', 'application_submitted', 'follow_up', 'research', 'meeting', 'other')",
        )
        batch_op.create_check_constraint(
            batch_op.f("activity_direction"),
            "direction IN ('outbound', 'inbound', 'internal')",
        )

    # ### end Alembic commands ###
