"""add job postings table

Revision ID: 5da6d2f60a12
Revises: f2921bc2aca0
Create Date: 2026-08-06 18:55:55.564121

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5da6d2f60a12"
down_revision = "f2921bc2aca0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_postings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("department", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column(
            "employment_type",
            sa.Enum(
                "full_time",
                "part_time",
                "contract",
                "internship",
                "temporary",
                name="employment_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "work_mode",
            sa.Enum(
                "on_site",
                "hybrid",
                "remote",
                name="work_mode",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("salary_min", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column("posting_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "company_website",
                "linkedin",
                "referral",
                "recruiter",
                "other",
                name="job_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("date_posted", sa.Date(), nullable=True),
        sa.Column("closing_date", sa.Date(), nullable=True),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "discovered",
                "researching",
                "ready_to_apply",
                "applied",
                "closed",
                "skipped",
                name="job_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "date_posted IS NULL OR closing_date IS NULL OR date_posted <= closing_date",
            name="ck_job_postings_date_range",
        ),
        sa.CheckConstraint(
            "priority BETWEEN 1 AND 5", name="ck_job_postings_priority_range"
        ),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max",
            name="ck_job_postings_salary_range",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_postings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_job_postings_closing_date", ["closing_date"], unique=False
        )
        batch_op.create_index(
            "ix_job_postings_date_posted", ["date_posted"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_postings_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_job_postings_organization_status",
            ["organization_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_job_postings_title"), ["title"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_postings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_postings_title"))
        batch_op.drop_index("ix_job_postings_organization_status")
        batch_op.drop_index(batch_op.f("ix_job_postings_organization_id"))
        batch_op.drop_index("ix_job_postings_date_posted")
        batch_op.drop_index("ix_job_postings_closing_date")

    op.drop_table("job_postings")
    # ### end Alembic commands ###
