"""add applications table

Revision ID: 77b925dec5cf
Revises: 5da6d2f60a12
Create Date: 2026-08-06 19:56:46.218647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b925dec5cf'
down_revision = '5da6d2f60a12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'preparing', 'applied', 'screening', 'phone_interview', 'technical_interview', 'panel_interview', 'final_interview', 'offer', 'accepted', 'rejected', 'withdrawn', name='application_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('resume_version', sa.String(length=1000), nullable=True),
    sa.Column('cover_letter_version', sa.String(length=1000), nullable=True),
    sa.Column('recruiter_name', sa.String(length=200), nullable=True),
    sa.Column('recruiter_email', sa.String(length=320), nullable=True),
    sa.Column('salary_requested', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_location', sa.String(length=300), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('offer_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('withdrawn', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('offer_salary IS NULL OR offer_salary > 0', name='ck_applications_offer_salary_positive'),
    sa.CheckConstraint('salary_requested IS NULL OR salary_requested > 0', name='ck_applications_salary_requested_positive'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_posting_id', name='uq_applications_job_posting_id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('ix_applications_application_date', ['application_date'], unique=False)
        batch_op.create_index('ix_applications_interview_date', ['interview_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_job_posting_id'), ['job_posting_id'], unique=False)
        batch_op.create_index('ix_applications_status', ['status'], unique=False)
        batch_op.create_index('ix_applications_updated_at', ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_updated_at')
        batch_op.drop_index('ix_applications_status')
        batch_op.drop_index(batch_op.f('ix_applications_job_posting_id'))
        batch_op.drop_index('ix_applications_interview_date')
        batch_op.drop_index('ix_applications_application_date')

    op.drop_table('applications')
    # ### end Alembic commands ###
