"""Create the initial User and Organization schema.

Revision ID: 83de6a00d447
Revises:
Create Date: 2026-08-06 18:15:27.553097

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "83de6a00d447"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "organization_type",
            sa.Enum(
                "hospital",
                "research_institute",
                "health_tech",
                "medical_device",
                "cro",
                "university",
                "recruiter",
                "government",
                name="organization_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority BETWEEN 1 AND 5", name="ck_organizations_priority_range"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index("ix_organizations_location", ["location"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_organizations_name"), ["name"], unique=True
        )
        batch_op.create_index(
            "ix_organizations_type", ["organization_type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index("ix_organizations_type")
        batch_op.drop_index(batch_op.f("ix_organizations_name"))
        batch_op.drop_index("ix_organizations_location")

    op.drop_table("organizations")
    op.drop_table("users")
    # ### end Alembic commands ###
