"""add tasks

Revision ID: 8ee3f8f631e0
Revises: 04a876bd029e
Create Date: 2026-08-06 20:35:03.514540

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8ee3f8f631e0"
down_revision = "04a876bd029e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.Column("job_posting_id", sa.Integer(), nullable=True),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "task_type",
            sa.Enum(
                "follow_up",
                "application",
                "interview_preparation",
                "research",
                "networking",
                "document_preparation",
                "thank_you",
                "portal_check",
                "reminder",
                "other",
                name="task_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "medium",
                "high",
                "urgent",
                name="task_priority",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "in_progress",
                "completed",
                "cancelled",
                name="task_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("due_time", sa.Time(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["job_posting_id"], ["job_postings.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tasks_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(
            "ix_tasks_application_status", ["application_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tasks_contact_id"), ["contact_id"], unique=False
        )
        batch_op.create_index(
            "ix_tasks_contact_status", ["contact_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tasks_due_date"), ["due_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tasks_job_posting_id"), ["job_posting_id"], unique=False
        )
        batch_op.create_index(
            "ix_tasks_job_status", ["job_posting_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tasks_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            "ix_tasks_organization_status", ["organization_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_tasks_status_due_date", ["status", "due_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tasks_title"), ["title"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_title"))
        batch_op.drop_index("ix_tasks_status_due_date")
        batch_op.drop_index("ix_tasks_organization_status")
        batch_op.drop_index(batch_op.f("ix_tasks_organization_id"))
        batch_op.drop_index("ix_tasks_job_status")
        batch_op.drop_index(batch_op.f("ix_tasks_job_posting_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_due_date"))
        batch_op.drop_index("ix_tasks_contact_status")
        batch_op.drop_index(batch_op.f("ix_tasks_contact_id"))
        batch_op.drop_index("ix_tasks_application_status")
        batch_op.drop_index(batch_op.f("ix_tasks_application_id"))

    op.drop_table("tasks")
    # ### end Alembic commands ###
