"""add contacts table

Revision ID: f2921bc2aca0
Revises: 83de6a00d447
Create Date: 2026-08-06 18:34:03.713804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2921bc2aca0'
down_revision = '83de6a00d447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('relationship_status', sa.Enum('new', 'contacted', 'responded', 'interviewing', 'long_term_connection', name='relationship_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_contacts_organization_last_name', ['organization_id', 'last_name'], unique=False)
        batch_op.create_index('ix_contacts_relationship_status', ['relationship_status'], unique=False)
        batch_op.create_index('ix_contacts_title', ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index('ix_contacts_title')
        batch_op.drop_index('ix_contacts_relationship_status')
        batch_op.drop_index('ix_contacts_organization_last_name')
        batch_op.drop_index(batch_op.f('ix_contacts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_last_name'))

    op.drop_table('contacts')
    # ### end Alembic commands ###
